dc01: 
  ansible_host: 10.10.1.2
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore


file_srv:
  ansible_host: 10.10.1.3
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore

debian:
  ansible_host: 10.10.1.4
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: ssh