- name: Configuration du DNS
  ansible.windows.win_dns_client: 
    adapter_names: "Ethernet 2"
    dns_servers: 127.0.0.1

- name: Add a network static route
  ansible.windows.win_command: route -p add 0.0.0.0 mask 0.0.0.0 10.10.1.1 metric 1


- name: Desactivation des firewall
  ansible.windows.win_powershell:
    script: |
      Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

- name: Installer le rôle Active Directory
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Promouvoir en contrôleur de domaine
  win_shell: |
    Import-Module ADDSDeployment
    $safeModeAdminstratorPassword = ConvertTo-SecureString 'Azertyuiop68.' -AsPlainText -Force
    Install-ADDSforest  -CreateDNSDelegation:$false -DatabasePath "C:\Windows\NTDS" -DOmainMode "Win2012" -DOmainName "irma.local" -DOmainNetbiosName "IRMA" -ForestMode "Win2012" -InstallDns:$true -LogPath "C:\Windows\NTDS" -NoRebootOnCompletion:$false -SysvolPath "C:\Windows\SYSVOL" -SafeModeAdministratorPassword $safeModeAdminstratorPassword -Force:$true

- name: Redémarrer la machine après l’installation du rôle AD-DS
  win_reboot:

- name: Modification du mot de passe Administrateur
  win_shell: 'net user Administrator Azertyuiop68.'
  become_user: 'Administrator'
  become_method: runas